version: '2'

services:
  ppc-linux-build:
    build: ./docker/linux_ppc_buildenv
    volumes:
      - ./output:/root/output:rw
      - ./files:/root/files:ro
    environment:
      - ARCH=powerpc
      - CROSS_COMPILE=powerpc-linux-gnu-
      - INSTALL_MOD_PATH=/root/output/rootfs/
      - INSTALL_PATH=/root/output/rootfs/boot/
    command: |
        bash -c "
          mkdir -p /root/output/rootfs/boot
          tar Jxf /root/files/linux-4.19.56.tar.xz
          mv linux* linux
          cd linux
          patch -p1 < /root/files/patches/0001-Add-dwc_otg-usb-driver-from-plathome-kernel.patch
          patch -p1 < /root/files/patches/0002-Replace-init_timer-to-timer_setup.patch
          patch -p1 < /root/files/patches/0003-convert-to-use-DRIVER_ATTR_RO-RW.patch
          patch -p1 < /root/files/patches/net.patcch
          cp /root/files/dot.config.4.1.8 .config
          cp /root/files/obs600.dts arch/powerpc/boot/dts/
          make olddefconfig
          make -j4
          cp arch/powerpc/boot/uImage.obs600 /root/output/rootfs/boot/
          make -j4 modules && make modules_install
          bash
        "

  gentoo_ppc_stage3:
    build: ./docker/gentoo_ppc_stage3
    volumes:
      - /usr/bin/qemu-ppc-static:/usr/bin/qemu-ppc-static
      - ./output/:/root/output
      - ./files:/root/files
    command: |
      bash -c "
        cd /root
        emerge-webrsync
        emerge rsync
        cp /root/files/fstab /etc/fstab
        rsync -v /root/output/rootfs/lib/modules/ /lib/modules/
        echo root | passwd --stdin root
      "
    

  tftp-server:
    image: pghalliday/tftp
    volumes:
      - ./tftp:/var/tftpboot:rw
    ports:
      - "0.0.0.0:69:69/udp"